## 첫 예제

In [2]:
import numpy as np

In [3]:
arr1 = np.array([0, 2, 5.5, 7])
print(arr1)

[0.  2.  5.5 7. ]


In [6]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
type(arr2)

numpy.ndarray

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [10]:
arr = a
arr

NameError: name 'a' is not defined

In [11]:
arr = 1

In [12]:
arr

1

In [13]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(5,)

In [16]:
arr.dtype

dtype('float64')

In [17]:
arr = np.zeros(shape = (6,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
for i in range(6):
    arr[i] = (i,i)
arr

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.]])

In [19]:
arr = np.zeros(shape = (6,2,2))
arr

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.empty(1)

array([2.45943152e+198])

In [65]:
np.empty((2,3), dtype=int)

array([[1572932080,        402,          0],
       [         0,     131074, 1763734377]])

In [29]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
np.eye(3,2, dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0]])

In [36]:
np.eye(5, k=1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.linspace(2.0, 3.0, num=7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [69]:
np.empty(1)

array([2.45943152e+198])

In [101]:
np.empty(3, dtype=float)

array([8.53819440e-312, 0.00000000e+000, 6.95208262e-310])

In [102]:
np.arange(5)
arr

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [103]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [104]:
type(arr)

numpy.ndarray

In [105]:
arr.shape

(5,)

In [106]:
np.arange(3,7)

array([3, 4, 5, 6])

In [107]:
np.arange(3,7,2)

array([3, 5])

In [108]:
arr = np.arange(5)

In [109]:
arr[3] = 10
arr

array([ 0,  1,  2, 10,  4])

In [110]:
arr[4] = 'kang'

ValueError: invalid literal for int() with base 10: 'kang'

In [111]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
arr.shape

(3, 4)

In [113]:
arr.reshape(-1)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
arr1 = arr.reshape(-1)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
arr.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [120]:
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [124]:
arr = np.array([[0,1,2], [3,4,5]])

In [125]:
type(arr)

numpy.ndarray

In [126]:
arr.shape

(2, 3)

In [127]:
arr.dtype

dtype('int32')

In [128]:
arr.size

6

In [129]:
arr.ndim

2

In [130]:
arr.itemsize

4

In [131]:
a = np.float32(5.0)
a

5.0

In [132]:
type(a)

numpy.float32

In [133]:
b = np.int_([1,2,3])

In [134]:
b

array([1, 2, 3])

In [135]:
type(b)

numpy.ndarray

In [138]:
arr = np.array([('kang', 25, 67), ('kim', 50, 70)],
              dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [139]:
arr

array([('kang', 25, 67.), ('kim', 50, 70.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [140]:
arr[0]

('kang', 25, 67.)

In [141]:
arr[1]

('kim', 50, 70.)

In [142]:
arr['age'] = 20

In [143]:
arr

array([('kang', 20, 67.), ('kim', 20, 70.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])