In [25]:
import pandas as pd
import numpy as np

In [2]:
house = pd.read_csv('C:/Users/ds/Desktop/파이썬/예제/src/house_price.csv')

In [3]:
house.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  CAT.MEDV  
0  396.90   4.98  24.0         0  
1  396.90   9.14  21.6         0  
2  392.83   4.03  34.7         1  
3  394.63   2.94  33.4         1  
4  396.90   5.33  36.2         1

In [4]:
house.isnull().sum()

CRIM        0
ZN          0
INDUS       0
CHAS        0
NOX         0
RM          0
AGE         0
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT       0
MEDV        0
CAT.MEDV    0
dtype: int64

In [5]:
drop_features = ['ZN','CHAS','RAD','CAT.MEDV']

In [6]:
house = house.drop(drop_features, axis=1)

In [7]:
house

CRIM  INDUS    NOX     RM   AGE     DIS  TAX  PTRATIO       B  LSTAT  \
0    0.00632   2.31  0.538  6.575  65.2  4.0900  296     15.3  396.90   4.98   
1    0.02731   7.07  0.469  6.421  78.9  4.9671  242     17.8  396.90   9.14   
2    0.02729   7.07  0.469  7.185  61.1  4.9671  242     17.8  392.83   4.03   
3    0.03237   2.18  0.458  6.998  45.8  6.0622  222     18.7  394.63   2.94   
4    0.06905   2.18  0.458  7.147  54.2  6.0622  222     18.7  396.90   5.33   
..       ...    ...    ...    ...   ...     ...  ...      ...     ...    ...   
501  0.06263  11.93  0.573  6.593  69.1  2.4786  273     21.0  391.99   9.67   
502  0.04527  11.93  0.573  6.120  76.7  2.2875  273     21.0  396.90   9.08   
503  0.06076  11.93  0.573  6.976  91.0  2.1675  273     21.0  396.90   5.64   
504  0.10959  11.93  0.573  6.794  89.3  2.3889  273     21.0  393.45   6.48   
505  0.04741  11.93  0.573  6.030  80.8  2.5050  273     21.0  396.90   7.88   

     MEDV  
0    24.0  
1    21.6  
2    34.7  
3    33.4  
4    36.2  
..    ...  
501  22.4  
502  20.6  
503  23.9  
504  22.0  
505  11.9  

[506 rows x 11 columns]

In [8]:
house_input = house[['CRIM','INDUS','NOX','RM','AGE','DIS','TAX','PTRATIO','B','LSTAT']].to_numpy()

In [9]:
house_input

array([[6.3200e-03, 2.3100e+00, 5.3800e-01, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 7.0700e+00, 4.6900e-01, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 7.0700e+00, 4.6900e-01, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 1.1930e+01, 5.7300e-01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 1.1930e+01, 5.7300e-01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 1.1930e+01, 5.7300e-01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [10]:
house_target = house['MEDV'].to_numpy()

In [19]:
from sklearn.model_selection import train_test_split

In [12]:
train_input, test_input, train_target, test_target = train_test_split(
house_input, house_target, random_state = 42)

In [20]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [21]:
randomF = RandomForestRegressor()

In [22]:
scores = cross_validate(randomF, train_input, train_target, 
                       return_train_score=True, n_jobs = -1)

In [23]:
scores

{'fit_time': array([0.77659249, 0.76263809, 0.80746388, 0.76765013, 0.72540164]),
 'score_time': array([0.01157045, 0.0135529 , 0.01006413, 0.01389503, 0.01190734]),
 'test_score': array([0.88036645, 0.79610924, 0.89063564, 0.88148898, 0.78230326]),
 'train_score': array([0.97859225, 0.97403681, 0.97782406, 0.9769233 , 0.97996858])}

In [26]:
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9774689990279188 0.8461807150947198


In [27]:
randomF.fit(train_input, train_target)

RandomForestRegressor()

In [34]:
print(randomF.score(train_input, train_target))
print(randomF.score(test_input, test_target))

0.9788337521234922
0.8564690580643378


In [30]:
randomF.predict(train_input)

array([37.376, 15.955, 45.235, 15.816, 23.116, 16.363, 18.479, 16.61 ,
       17.675, 20.315, 31.912, 28.91 , 16.245, 17.901, 23.171, 19.59 ,
       18.674,  8.164, 20.846, 17.159, 15.775, 14.886, 47.83 , 14.739,
       13.798, 26.641, 21.074, 19.485, 22.19 , 18.39 , 24.202, 34.424,
        6.958, 26.525, 19.008, 21.217, 23.184, 21.443, 21.83 , 47.926,
       14.488, 17.191, 22.937, 20.309, 19.99 , 21.076, 39.139, 21.947,
       20.162, 19.435, 28.807, 36.069, 24.561, 12.561, 12.7  , 11.554,
       16.59 , 32.527, 26.678, 13.919, 14.151, 46.701, 21.428, 20.235,
       23.048, 18.311, 12.272,  6.627, 30.965, 26.319, 19.294, 16.009,
       14.148, 22.942, 17.155, 27.529, 35.179, 23.171, 24.265, 23.64 ,
       48.818, 34.137, 31.612, 24.07 , 22.472, 14.73 , 41.695, 19.619,
       31.905, 25.199, 20.94 , 21.391,  8.945, 45.713, 43.136, 31.861,
        9.246, 16.554, 20.533, 33.889, 16.82 , 43.474, 21.004, 23.223,
       12.541, 19.81 , 24.265, 29.851, 28.492, 22.381, 30.505, 25.823,
      

In [31]:
randomF.predict(test_input)

array([22.695, 31.323, 16.682, 23.77 , 16.785, 21.13 , 19.158, 15.777,
       21.511, 21.182, 20.189, 19.323,  8.94 , 21.263, 19.292, 26.174,
       18.543,  8.511, 45.358, 14.875, 24.065, 23.86 , 14.691, 23.953,
       14.842, 15.117, 21.46 , 14.067, 18.972, 20.551, 19.858, 23.479,
       30.792, 20.256, 14.81 , 16.178, 34.644, 19.148, 20.72 , 24.101,
       19.656, 29.008, 44.83 , 19.224, 22.293, 13.304, 15.094, 24.468,
       18.583, 28.538, 21.637, 33.894, 16.602, 25.967, 45.902, 21.601,
       14.947, 32.225, 21.948, 20.804, 25.04 , 34.008, 30.433, 18.805,
       27.25 , 17.572, 13.399, 23.056, 29.233, 15.638, 20.64 , 28.065,
       10.711, 21.567, 21.985,  7.329, 20.184, 45.495, 10.971, 13.333,
       21.602, 11.478, 20.663,  9.432, 20.734, 27.105, 15.652, 23.351,
       23.776, 17.746, 21.892,  7.998, 19.449, 19.428, 21.903, 19.684,
       38.141, 11.444, 12.668, 12.303, 20.225, 23.399, 13.758, 20.19 ,
       21.878, 12.604, 19.424, 24.639, 20.089, 23.243,  8.92 , 16.013,
      